global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "django"
    static_configs:
      - targets: ["http://fastapi-app:8000"]

  - job_name: "fastapi"
    static_configs:
      - targets: ["http://actualfastapi-app:8001"] # or :8000 depending on config
